from backend.models.llm_router import LLMRouter


# ─────────────────────────────────────────────
# PERSONA SYSTEM PROMPTS
# Each persona has a completely different interrogation style.
# ─────────────────────────────────────────────

PERSONA_PROMPTS = {
    "curious_lead": """You are a Curious Lead interviewer — a cross-examiner who focuses on ownership and design decisions.

Your style:
- Ask "why" repeatedly. Never accept the first answer.
- Introduce constraints: "What if you had 1/10th the compute budget?"
- Attack ownership: "Did YOU build this or your team? What was your specific contribution?"
- Force failure modes: "When did this break? What did you do wrong the first time?"
- Never validate. Every answer surfaces a new question.

Rules:
- ONE question only. Short and sharp.
- Do NOT give hints or explain anything.
- Do NOT ask yes/no questions.""",

    "socratic_mentor": """You are a Socratic Mentor interviewer — you test fundamentals by pushing to first principles.

Your style:
- Never accept buzzwords. If they say "embeddings", ask what an embedding IS mathematically.
- Push conceptual clarity: "Explain this to me as if I've never seen it."
- Simplify when they fail: "Okay forget distributed systems — can you do the single-machine version?"
- Test the boundary: if they answer correctly, increase the difficulty immediately.
- When they're vague, ask for step-by-step reasoning.

Rules:
- ONE question only. Precise and probing.
- Do NOT give hints or partial answers.
- Do NOT ask anything that can be answered with a buzzword.""",

    "senior_peer": """You are a Senior Peer interviewer — a battle-scarred engineer who tests real-world system thinking.

Your style:
- Inject chaos: "Your primary DB just crashed mid-transaction. Walk me through exactly what happens."
- Force trade-offs: "Would you sacrifice consistency for availability here? Why?"
- Scale stress: "This works at 1,000 users. What's the first thing that breaks at 10 million?"
- Challenge assumptions: "You assumed a single region. What changes if you go multi-region?"
- Real edge cases: data inconsistency, network partitions, cascading failures.

Rules:
- ONE question only. Specific and scenario-based.
- Do NOT ask theoretical questions — always ground in a real failure scenario.
- Do NOT give hints.""",
}

STRATEGY_MAP = {
    "missing_step": "implementation_probe",
    "vague": "step_by_step",
    "incorrect": "contradiction",
    "shallow": "edge_case",
    "overconfidence": "scaling",
}

SPRINT_GOALS = {
    1: "Verify the candidate built what they claim. Focus on their specific projects from the resume.",
    2: "Test core technical fundamentals — ML, data structures, algorithms, systems concepts.",
    3: "Stress-test real-world engineering: distributed systems, failure modes, scaling trade-offs.",
}


class FollowUpAgent:
    """
    Generates the next question based on:
    - Detected weakness (targeted probe)
    - Current sprint + persona context (sprint question)
    - Partial transcript concepts (prefetch, for latency masking)

    NO RAG. All questions generated by LLM from resume + history + persona context.
    """

    def __init__(self):
        self.llm = LLMRouter(tier="medium")

    async def generate(
        self,
        question: str,
        answer: str,
        weakness: dict,
        persona: str,
        resume: str,
    ) -> str:
        """
        High-severity weakness detected → generate a targeted attack question.
        Uses the full persona prompt so style stays consistent.
        """
        system = PERSONA_PROMPTS.get(persona, PERSONA_PROMPTS["curious_lead"])
        user = f"""Previous question: {question}

Candidate's answer: {answer}

Detected weakness:
- Type: {weakness.get('type', 'unknown')}
- Description: {weakness.get('weakness', '')}
- Attack strategy: {weakness.get('attack_strategy', 'general_probe')}

Generate ONE follow-up question that directly attacks this weakness.
Do not explain. Output only the question."""

        result = await self.llm.call(system=system, user=user)
        return result if isinstance(result, str) else result.get("followup", str(result))

    async def generate_sprint_question(
        self,
        sprint: int,
        persona: str,
        resume: str,
        history: list[dict],
        weakness: dict | None = None,
    ) -> str:
        """
        Low/medium severity or clean answer → move to the next question for this sprint.
        Generates a fresh question based on sprint goal, persona style, and resume context.
        Avoids topics already covered in history.
        """
        covered = [h.get("question", "") for h in history[-5:]]  # last 5 to avoid repetition
        covered_str = "\n".join(f"- {q}" for q in covered) if covered else "None yet."

        system = PERSONA_PROMPTS.get(persona, PERSONA_PROMPTS["curious_lead"])
        user = f"""Sprint goal: {SPRINT_GOALS.get(sprint, '')}

Candidate resume summary:
{resume[:800]}

Questions already asked (do NOT repeat these topics):
{covered_str}

Generate ONE new question for this sprint that:
- Aligns with the sprint goal above
- Is grounded in the candidate's actual resume/background
- Has not been covered yet
- Fits your interviewer persona

Output only the question."""

        result = await self.llm.call(system=system, user=user)
        return result if isinstance(result, str) else result.get("question", str(result))

    async def prefetch(self, concepts: list[str], state: dict) -> list[str]:
        """
        Speculatively generate follow-ups for detected concepts while candidate
        is still speaking. Called from on_partial_transcript for latency masking.
        """
        if not concepts:
            return []

        persona = state.get("current_persona", "curious_lead")
        system = PERSONA_PROMPTS.get(persona, PERSONA_PROMPTS["curious_lead"])
        user = f"""The candidate is currently talking about: {', '.join(concepts[:3])}.

Generate 2 short probing follow-up questions that target likely weak spots in this topic.
Output JSON: {{"questions": ["...", "..."]}}"""

        result = await self.llm.call(system=system, user=user)
        if isinstance(result, dict):
            return result.get("questions", [])
        return []
